### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by mfurquimdev** [rapiz1/catp#4]
Hi,

I really like the idea of the project and I would like to try it. But I could not find on the Arch Linux repository to install.

I'm not familiar with rust. Can we have a small **how to install** on this project?

I appreciate it.

**Comment by yujqiao** [comment]
You can download from release and use the binary directly. Or add it to your PATH.



---Original---
From: "Mateus ***@***.***&gt;
Date: Wed, Jul 27, 2022 20:13 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [rapiz1/catp] How to install (Issue #4)




 
Hi,
 
I really like the idea and I would like to try it. But I could not find on the Arch Linux repository to install.
 
I'm not familiar with rust. Can we have a small how to install on this project?
 
I appreciate it.

**Comment by mfurquimdev** [comment]
Yes, it worked!

Thank you, @rapiz1 :)

**Comment by yujqiao** [comment]
README has been updated to point to release. Closing now

**Comment by hartmark** [comment]
I have created a aur-package for it for arch linux:
https://aur.archlinux.org/packages/catp

I also created a package that tracks main branch:
https://aur.archlinux.org/packages/catp-git

I noted however that the --version prints 0.2.0 also from the main branch, it should preferably print the git commit hash.
